box2の説明文を追加（使用しない）行の段差を修正
u-lab/polyzome pull request #7
Opened 2021-09-08 14:09 UTC by tomori2226

box2の説明文を追加しました。関数は無暗に増やさないという方針でbox2は使わないことになりました。
先輩に指摘された、行の改行を入れています。

2021-09-08 14:13 UTC, tomori2226 commented
会議後の内容を反映しています。
新しい内容は入っていません。

2021-09-08 14:40 UTC, HinataKikuchi reviewed
できる範囲で実装してみてくださいー！

2021-09-08 14:40 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +void test_drawBox_var2(int x, int y, float radius, bool fillFg){
んー、今後使うことはないかもしれませんが練習がてら使いやすくなるコツだけ書いときますね。

1. delayの値をユーザーが引数で任意に指定できるようにしてみる。
2. delayをそもそも入れるかどうかをユーザーが指定できるようにしてみる。

チョットここら辺を見ながら、どうやったら汎用性が上がるか考えてみてくださいー
その修正を見てから反映するか消すか考えますー！

2021-09-10 03:24 UTC, HinataKikuchi requested changes
内容を見ながら後でレビューしよーね！

2021-09-10 03:24 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +  ** 引数 : bool fillfg,int delaytime, int delaytime, bool delay_on  : boxの中を埋める(true),埋めない(false) delaytimeでdelay時間を入力、delay時間がいる場合(delay_on),いらない場合(false)
箇条書きがいいなー！

2021-09-10 03:24 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +  if(delay_on){
delayの直前だけにif文を置いてあげれば、131からのコードはいらなくならない？

2021-09-10 03:24 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +if(false){
この書き方はだめだよー、何がfalseかわからないよー？(あとif(false)は常に実行されない、if(true)は常に実行されるから意味がないー)

2021-09-10 03:24 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +
意図の説明くださーい

2021-09-10 04:11 UTC, tomori2226 commented on rain/sawai_main.ino
> +  if(delay_on){
なるほど！！

2021-09-10 04:12 UTC, tomori2226 commented on rain/sawai_main.ino
> +if(false){
分かりました。
今日の話で詳しくお話をお願いします。

2021-09-10 04:53 UTC, tomori2226 commented on rain/sawai_main.ino
> +
後ろの方で光の点灯を打ち込むのが面倒なので関数として使おうという試みです。

2021-09-10 05:49 UTC, HinataKikuchi requested changes
スペルミス、インデント、カッコ忘れに注意～(自戒)

2021-09-10 05:49 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +if(false){
delay(time)じゃなくてdelay(delaytime)だよー！

2021-09-10 05:49 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +
書いといてー！

2021-09-10 05:55 UTC, HinataKikuchi commented on rain/sawai_main.ino
> +  ** 引数 : bool fillfg,int delaytime, int delaytime, bool delay_on  : boxの中を埋める(true),埋めない(false) delaytimeでdelay時間を入力、delay時間がいる場合(delay_on),いらない場合(false)
```
** 引数 : 引数1 : 引数1の説明,
              引数2 : 引数2の説明,
...
              引数n : 引数nの説明
```
みたいなことをしてほしい！

2021-09-11 03:33 UTC, HinataKikuchi reviewed
ちょこっとだけ見てー

2021-09-11 03:33 UTC, HinataKikuchi commented on rain/sawai_main.ino
>        delay(delaytime);
実行内容の前にはtabが欲しいよー
```
if (条件)
    条件==trueの時の実行内容;
```

2021-09-11 07:37 UTC, tomori2226 commented on rain/sawai_main.ino
>        delay(delaytime);
修正しました

2021-09-11 09:16 UTC, HinataKikuchi approved these changes
![LGTM](https://image.lgtmoon.dev/124451)

2021-09-11 09:16 UTC, merged